### PR TITLE
Reorganize repo contents for Landr

### PR DESCRIPTION
**Pull request by dimitrisnl**

### CODE REVIEW

**Comment by dimitrisnl** [comment]
**I've included the build files, but this is temporary**

https://balena-dash.netlify.com/

- Added Highlights (placeholder)
- Moved Readme sections to /docs folder
- Included Hardware required section
- Included Software required section
- Included Introduction section (has no title, needs visual work)

**Comment by dimitrisnl** [comment]
@chrisys Any ideas for this section?

Screen Shot 2019-10-22 at 11 15 15 AM

See the 'Highlights' section in the Readme. We can drop this if nothing comes to mind.

**Comment by chrisys** [comment]
@dimitrisnl for this particular one, what about project ideas, so...

**Photo frame**
Build a photo frame as a gift for remote friends and family, add new photos and media remotely.

**Dashboards**
Set up remotely managed dashboards for home automation, weather, news, business information and more!

**Live video streams**
Create live video feeds to monitor camera feeds, webcams, YouTube videos etc.

**Comment by dimitrisnl** [comment]
Awesome, updated!

**Pull request closed without merging**
