### PR TITLE
Create balena.yml

### PR DESCRIPTION
**Pull request by phil-d-wilson**
Change-type: patch
Signed-off-by: Phil Wilson <phil@balena.io>

### CODE REVIEW

**Comment by phil-d-wilson** [comment]
@chrisys please could you add a balena API key to the registry secrets of this repo - or make me an admin on this GH org, so that I can add the GH action to all the projects.

Ta.

**Comment by chrisys** [comment]
@phil-d-wilson will do! 😁

**Comment by chrisys** [comment]
@balena-ci I self-certify!

**Comment by chrisys** [comment]
@balena-ci I self-certify!

**Comment by chrisys** [comment]
You cannot be serious

**Pull request merged**
