### PR TITLE
Add support for x64 devices

### PR DESCRIPTION
**Pull request by rahul-thakoor**
Add support for x64 devices where kiosk uses chromium browser. 
Scheduler uses `vbetool` to turn screen on/off

Connects-to: #68 
Change-type: minor
Signed-off-by: Rahul Thakoor <rahul@balena.io>

### CODE REVIEW

**Comment by rahul-thakoor** [comment]
@chrisys I've made some changes regarding scheduler service for `amd64`

**Comment by chrisys** [comment]
LGTM in terms of code changes @rahul-thakoor but I haven't tested it on a real device. Much tidier without those if statements!

**Comment by rahul-thakoor** [comment]
hey @jtonello @alanb128 can I please get another review with recent changes?

**Comment by jtonello** [comment]
Everything works as expected, including setting the TZ variable and automating backlight_on and backlight_off.

**Pull request merged**
