### PR TITLE
Adding components for balenaDash Landr

### PR DESCRIPTION
**Pull request by andrewnhem**
This feature adds the components to create a Landr site for balenaDash.
No breaking changes were made, but readme on project repo might look a bit different.
Big chance that this might not build, but at least the work has started.

New services added:
- adding and refactoring components to build page with Landr
- first run at content to landr-ify balenaDash (work in progress)

Change-type: major
Signed-off-b y: Andrew Nhem <andrewn@balena.io>

### CODE REVIEW

**Comment by iamsolankiamit** [comment]
@balena-ci retest

**Comment by iamsolankiamit** [comment]
@balena-ci retest

**Comment by iamsolankiamit** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by cmfcruz** [comment]
@balena-ci rebase

**Comment by cmfcruz** [comment]
I resolved the conflict in the README file.  This should avoid the versionbot error.

**Comment by iamsolankiamit** [comment]
@balena-ci retest

**Comment by cmfcruz** [comment]
@balena-ci retest

**Comment by cmfcruz** [comment]
@iamsolankiamit I am going to close this PR and just create a new PR that links back to this one.  I need to test how landr generates the site upon opening the PR.  I'll use the same branch.

**Pull request closed without merging**
